/*****************************************************************************
*
* Copyright (c) 2000 - 2008, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400142
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include "QvisPoincarePlotWindow.h"

#include <PoincareAttributes.h>
#include <ViewerProxy.h>

#include <qcheckbox.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <qspinbox.h>
#include <qvbox.h>
#include <qbuttongroup.h>
#include <qradiobutton.h>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineStyleWidget.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>

#include <stdio.h>
#include <string>

using std::string;

// ****************************************************************************
// Method: QvisPoincarePlotWindow::QvisPoincarePlotWindow
//
// Purpose: 
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPoincarePlotWindow::QvisPoincarePlotWindow(const int type,
                         PoincareAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisPostableWindowObserver(subj, caption, shortName, notepad)
{
    plotType = type;
    atts = subj;
}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::~QvisPoincarePlotWindow
//
// Purpose: 
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPoincarePlotWindow::~QvisPoincarePlotWindow()
{
}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::CreateWindowContents
//
// Purpose: 
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::CreateWindowContents()
{
    QGridLayout *mainLayout = new QGridLayout(topLayout, 30,2,  10, "mainLayout");


    sourceTypeLabel = new QLabel(tr("Streamline Source"), central, "sourceTypeLabel");
    mainLayout->addWidget(sourceTypeLabel,0,0);
    sourceType = new QButtonGroup(central, "sourceType");
    sourceType->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *sourceTypeLayout = new QHBoxLayout(sourceType);
    sourceTypeLayout->setSpacing(10);
    QRadioButton *sourceTypeSourceTypeSpecifiedPoint = new QRadioButton(tr("SpecifiedPoint"), sourceType);
    sourceTypeLayout->addWidget(sourceTypeSourceTypeSpecifiedPoint);
    QRadioButton *sourceTypeSourceTypeSpecifiedLine = new QRadioButton(tr("SpecifiedLine"), sourceType);
    sourceTypeLayout->addWidget(sourceTypeSourceTypeSpecifiedLine);
    QRadioButton *sourceTypeSourceTypeSpecifiedPlane = new QRadioButton(tr("SpecifiedPlane"), sourceType);
    sourceTypeLayout->addWidget(sourceTypeSourceTypeSpecifiedPlane);
    connect(sourceType, SIGNAL(clicked(int)),
            this, SLOT(sourceTypeChanged(int)));
    mainLayout->addWidget(sourceType, 0,1);

    maxStepLengthLabel = new QLabel(tr("maximum step length"), central, "maxStepLengthLabel");
    mainLayout->addWidget(maxStepLengthLabel,1,0);
    maxStepLength = new QLineEdit(central, "maxStepLength");
    connect(maxStepLength, SIGNAL(returnPressed()),
            this, SLOT(maxStepLengthProcessText()));
    mainLayout->addWidget(maxStepLength, 1,1);

    terminationLabel = new QLabel(tr("Termination"), central, "terminationLabel");
    mainLayout->addWidget(terminationLabel,2,0);
    termination = new QLineEdit(central, "termination");
    connect(termination, SIGNAL(returnPressed()),
            this, SLOT(terminationProcessText()));
    mainLayout->addWidget(termination, 2,1);

    pointSourceLabel = new QLabel(tr("Point Source"), central, "pointSourceLabel");
    mainLayout->addWidget(pointSourceLabel,3,0);
    pointSource = new QLineEdit(central, "pointSource");
    connect(pointSource, SIGNAL(returnPressed()),
            this, SLOT(pointSourceProcessText()));
    mainLayout->addWidget(pointSource, 3,1);

    lineStartLabel = new QLabel(tr("Line Point Start"), central, "lineStartLabel");
    mainLayout->addWidget(lineStartLabel,4,0);
    lineStart = new QLineEdit(central, "lineStart");
    connect(lineStart, SIGNAL(returnPressed()),
            this, SLOT(lineStartProcessText()));
    mainLayout->addWidget(lineStart, 4,1);

    lineEndLabel = new QLabel(tr("Line Point End"), central, "lineEndLabel");
    mainLayout->addWidget(lineEndLabel,5,0);
    lineEnd = new QLineEdit(central, "lineEnd");
    connect(lineEnd, SIGNAL(returnPressed()),
            this, SLOT(lineEndProcessText()));
    mainLayout->addWidget(lineEnd, 5,1);

    planeOriginLabel = new QLabel(tr("Plane Source Point"), central, "planeOriginLabel");
    mainLayout->addWidget(planeOriginLabel,6,0);
    planeOrigin = new QLineEdit(central, "planeOrigin");
    connect(planeOrigin, SIGNAL(returnPressed()),
            this, SLOT(planeOriginProcessText()));
    mainLayout->addWidget(planeOrigin, 6,1);

    planeNormalLabel = new QLabel(tr("Plane Source Normal"), central, "planeNormalLabel");
    mainLayout->addWidget(planeNormalLabel,7,0);
    planeNormal = new QLineEdit(central, "planeNormal");
    connect(planeNormal, SIGNAL(returnPressed()),
            this, SLOT(planeNormalProcessText()));
    mainLayout->addWidget(planeNormal, 7,1);

    planeUpAxisLabel = new QLabel(tr("Plane Source Up Axis"), central, "planeUpAxisLabel");
    mainLayout->addWidget(planeUpAxisLabel,8,0);
    planeUpAxis = new QLineEdit(central, "planeUpAxis");
    connect(planeUpAxis, SIGNAL(returnPressed()),
            this, SLOT(planeUpAxisProcessText()));
    mainLayout->addWidget(planeUpAxis, 8,1);

    legendFlag = new QCheckBox(tr("Legend"), central, "legendFlag");
    connect(legendFlag, SIGNAL(toggled(bool)),
            this, SLOT(legendFlagChanged(bool)));
    mainLayout->addWidget(legendFlag, 9,0);

    lightingFlag = new QCheckBox(tr("Lighting"), central, "lightingFlag");
    connect(lightingFlag, SIGNAL(toggled(bool)),
            this, SLOT(lightingFlagChanged(bool)));
    mainLayout->addWidget(lightingFlag, 10,0);

    relTolLabel = new QLabel(tr("rel. tolerance"), central, "relTolLabel");
    mainLayout->addWidget(relTolLabel,11,0);
    relTol = new QLineEdit(central, "relTol");
    connect(relTol, SIGNAL(returnPressed()),
            this, SLOT(relTolProcessText()));
    mainLayout->addWidget(relTol, 11,1);

    absTolLabel = new QLabel(tr("abs. tolerance"), central, "absTolLabel");
    mainLayout->addWidget(absTolLabel,12,0);
    absTol = new QLineEdit(central, "absTol");
    connect(absTol, SIGNAL(returnPressed()),
            this, SLOT(absTolProcessText()));
    mainLayout->addWidget(absTol, 12,1);

    terminationTypeLabel = new QLabel(tr("Termination Type"), central, "terminationTypeLabel");
    mainLayout->addWidget(terminationTypeLabel,13,0);
    terminationType = new QButtonGroup(central, "terminationType");
    terminationType->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *terminationTypeLayout = new QHBoxLayout(terminationType);
    terminationTypeLayout->setSpacing(10);
    QRadioButton *terminationTypeTerminationTypeDistance = new QRadioButton(tr("Distance"), terminationType);
    terminationTypeLayout->addWidget(terminationTypeTerminationTypeDistance);
    QRadioButton *terminationTypeTerminationTypeTime = new QRadioButton(tr("Time"), terminationType);
    terminationTypeLayout->addWidget(terminationTypeTerminationTypeTime);
    QRadioButton *terminationTypeTerminationTypeStep = new QRadioButton(tr("Step"), terminationType);
    terminationTypeLayout->addWidget(terminationTypeTerminationTypeStep);
    connect(terminationType, SIGNAL(clicked(int)),
            this, SLOT(terminationTypeChanged(int)));
    mainLayout->addWidget(terminationType, 13,1);

    integrationTypeLabel = new QLabel(tr("Integrator"), central, "integrationTypeLabel");
    mainLayout->addWidget(integrationTypeLabel,14,0);
    integrationType = new QButtonGroup(central, "integrationType");
    integrationType->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *integrationTypeLayout = new QHBoxLayout(integrationType);
    integrationTypeLayout->setSpacing(10);
    QRadioButton *integrationTypeIntegrationTypeDormandPrince = new QRadioButton(tr("DormandPrince"), integrationType);
    integrationTypeLayout->addWidget(integrationTypeIntegrationTypeDormandPrince);
    QRadioButton *integrationTypeIntegrationTypeAdamsBashforth = new QRadioButton(tr("AdamsBashforth"), integrationType);
    integrationTypeLayout->addWidget(integrationTypeIntegrationTypeAdamsBashforth);
    connect(integrationType, SIGNAL(clicked(int)),
            this, SLOT(integrationTypeChanged(int)));
    mainLayout->addWidget(integrationType, 14,1);

    showStreamlines = new QCheckBox(tr("Show Streamlines"), central, "showStreamlines");
    connect(showStreamlines, SIGNAL(toggled(bool)),
            this, SLOT(showStreamlinesChanged(bool)));
    mainLayout->addWidget(showStreamlines, 15,0);

    showPoints = new QCheckBox(tr("Show Points"), central, "showPoints");
    connect(showPoints, SIGNAL(toggled(bool)),
            this, SLOT(showPointsChanged(bool)));
    mainLayout->addWidget(showPoints, 16,0);

    pointDensityLabel = new QLabel(tr("Point Density"), central, "pointDensityLabel");
    mainLayout->addWidget(pointDensityLabel,17,0);
    pointDensity = new QLineEdit(central, "pointDensity");
    connect(pointDensity, SIGNAL(returnPressed()),
            this, SLOT(pointDensityProcessText()));
    mainLayout->addWidget(pointDensity, 17,1);

    sourceRadiusLabel = new QLabel(tr("Source Radius"), central, "sourceRadiusLabel");
    mainLayout->addWidget(sourceRadiusLabel,18,0);
    sourceRadius = new QLineEdit(central, "sourceRadius");
    connect(sourceRadius, SIGNAL(returnPressed()),
            this, SLOT(sourceRadiusProcessText()));
    mainLayout->addWidget(sourceRadius, 18,1);

    colorTableNameLabel = new QLabel(tr("Color table"), central, "colorTableNameLabel");
    mainLayout->addWidget(colorTableNameLabel,19,0);
    colorTableName = new QvisColorTableButton(central, "colorTableName");
    connect(colorTableName, SIGNAL(selectedColorTable(bool, const QString&)),
            this, SLOT(colorTableNameChanged(bool, const QString&)));
    mainLayout->addWidget(colorTableName, 19,1);

    singleColorLabel = new QLabel(tr("Single color"), central, "singleColorLabel");
    mainLayout->addWidget(singleColorLabel,20,0);
    singleColor = new QvisColorButton(central, "singleColor");
    connect(singleColor, SIGNAL(selectedColor(const QColor&)),
            this, SLOT(singleColorChanged(const QColor&)));
    mainLayout->addWidget(singleColor, 20,1);

    NumberPlanesLabel = new QLabel(tr("NumberPlanes"), central, "NumberPlanesLabel");
    mainLayout->addWidget(NumberPlanesLabel,21,0);
    NumberPlanes = new QLineEdit(central, "NumberPlanes");
    connect(NumberPlanes, SIGNAL(returnPressed()),
            this, SLOT(NumberPlanesProcessText()));
    mainLayout->addWidget(NumberPlanes, 21,1);

    ColorStyleLabel = new QLabel(tr("ColorStyle value"), central, "ColorStyleLabel");
    mainLayout->addWidget(ColorStyleLabel,22,0);
    ColorStyle = new QButtonGroup(central, "ColorStyle");
    ColorStyle->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *ColorStyleLayout = new QHBoxLayout(ColorStyle);
    ColorStyleLayout->setSpacing(10);
    QRadioButton *ColorStyleColorStyleTypeOriginalValue = new QRadioButton(tr("OriginalValue"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeOriginalValue);
    QRadioButton *ColorStyleColorStyleTypeInputOrder = new QRadioButton(tr("InputOrder"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeInputOrder);
    QRadioButton *ColorStyleColorStyleTypePointIndex = new QRadioButton(tr("PointIndex"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypePointIndex);
    QRadioButton *ColorStyleColorStyleTypePlane = new QRadioButton(tr("Plane"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypePlane);
    QRadioButton *ColorStyleColorStyleTypeToroidalWindingOrder = new QRadioButton(tr("ToroidalWindingOrder"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeToroidalWindingOrder);
    QRadioButton *ColorStyleColorStyleTypeToroidalWindingPointOrder = new QRadioButton(tr("ToroidalWindingPointOrder"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeToroidalWindingPointOrder);
    QRadioButton *ColorStyleColorStyleTypeToroidalWindings = new QRadioButton(tr("ToroidalWindings"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeToroidalWindings);
    QRadioButton *ColorStyleColorStyleTypePoloidalWindings = new QRadioButton(tr("PoloidalWindings"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypePoloidalWindings);
    QRadioButton *ColorStyleColorStyleTypeSafetyFactor = new QRadioButton(tr("SafetyFactor"), ColorStyle);
    ColorStyleLayout->addWidget(ColorStyleColorStyleTypeSafetyFactor);
    connect(ColorStyle, SIGNAL(clicked(int)),
            this, SLOT(ColorStyleChanged(int)));
    mainLayout->addWidget(ColorStyle, 22,1);

    MaxToroidalWindingLabel = new QLabel(tr("MaxToroidalWinding"), central, "MaxToroidalWindingLabel");
    mainLayout->addWidget(MaxToroidalWindingLabel,23,0);
    MaxToroidalWinding = new QLineEdit(central, "MaxToroidalWinding");
    connect(MaxToroidalWinding, SIGNAL(returnPressed()),
            this, SLOT(MaxToroidalWindingProcessText()));
    mainLayout->addWidget(MaxToroidalWinding, 23,1);

    OverrideToroidalWindingLabel = new QLabel(tr("OverrideToroidalWinding"), central, "OverrideToroidalWindingLabel");
    mainLayout->addWidget(OverrideToroidalWindingLabel,24,0);
    OverrideToroidalWinding = new QLineEdit(central, "OverrideToroidalWinding");
    connect(OverrideToroidalWinding, SIGNAL(returnPressed()),
            this, SLOT(OverrideToroidalWindingProcessText()));
    mainLayout->addWidget(OverrideToroidalWinding, 24,1);

    HitRateLabel = new QLabel(tr("HitRate"), central, "HitRateLabel");
    mainLayout->addWidget(HitRateLabel,25,0);
    HitRate = new QLineEdit(central, "HitRate");
    connect(HitRate, SIGNAL(returnPressed()),
            this, SLOT(HitRateProcessText()));
    mainLayout->addWidget(HitRate, 25,1);

    ShowCurvesLabel = new QLabel(tr("ShowCurves"), central, "ShowCurvesLabel");
    mainLayout->addWidget(ShowCurvesLabel,26,0);
    ShowCurves = new QButtonGroup(central, "ShowCurves");
    ShowCurves->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *ShowCurvesLayout = new QHBoxLayout(ShowCurves);
    ShowCurvesLayout->setSpacing(10);
    QRadioButton *ShowCurvesShowMeshTypeCurves = new QRadioButton(tr("Curves"), ShowCurves);
    ShowCurvesLayout->addWidget(ShowCurvesShowMeshTypeCurves);
    QRadioButton *ShowCurvesShowMeshTypeSurfaces = new QRadioButton(tr("Surfaces"), ShowCurves);
    ShowCurvesLayout->addWidget(ShowCurvesShowMeshTypeSurfaces);
    connect(ShowCurves, SIGNAL(clicked(int)),
            this, SLOT(ShowCurvesChanged(int)));
    mainLayout->addWidget(ShowCurves, 26,1);

    AdjustPlaneLabel = new QLabel(tr("AdjustPlane"), central, "AdjustPlaneLabel");
    mainLayout->addWidget(AdjustPlaneLabel,27,0);
    AdjustPlane = new QLineEdit(central, "AdjustPlane");
    connect(AdjustPlane, SIGNAL(returnPressed()),
            this, SLOT(AdjustPlaneProcessText()));
    mainLayout->addWidget(AdjustPlane, 27,1);

    ShowIslands = new QCheckBox(tr("ShowIslands"), central, "ShowIslands");
    connect(ShowIslands, SIGNAL(toggled(bool)),
            this, SLOT(ShowIslandsChanged(bool)));
    mainLayout->addWidget(ShowIslands, 28,0);

    OverlapsLabel = new QLabel(tr("Overlaps"), central, "OverlapsLabel");
    mainLayout->addWidget(OverlapsLabel,29,0);
    Overlaps = new QButtonGroup(central, "Overlaps");
    Overlaps->setFrameStyle(QFrame::NoFrame);
    QHBoxLayout *OverlapsLayout = new QHBoxLayout(Overlaps);
    OverlapsLayout->setSpacing(10);
    QRadioButton *OverlapsOverlapTypeRaw = new QRadioButton(tr("Raw"), Overlaps);
    OverlapsLayout->addWidget(OverlapsOverlapTypeRaw);
    QRadioButton *OverlapsOverlapTypeRemove = new QRadioButton(tr("Remove"), Overlaps);
    OverlapsLayout->addWidget(OverlapsOverlapTypeRemove);
    QRadioButton *OverlapsOverlapTypeMerge = new QRadioButton(tr("Merge"), Overlaps);
    OverlapsLayout->addWidget(OverlapsOverlapTypeMerge);
    QRadioButton *OverlapsOverlapTypeSmooth = new QRadioButton(tr("Smooth"), Overlaps);
    OverlapsLayout->addWidget(OverlapsOverlapTypeSmooth);
    connect(Overlaps, SIGNAL(clicked(int)),
            this, SLOT(OverlapsChanged(int)));
    mainLayout->addWidget(Overlaps, 29,1);

}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::UpdateWindow
//
// Purpose: 
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::UpdateWindow(bool doAll)
{
    QString temp;
    double r;

    for(int i = 0; i < atts->NumAttributes(); ++i)
    {
        if(!doAll)
        {
            if(!atts->IsSelected(i))
            {
                continue;
            }
        }

        const double         *dptr;
        const float          *fptr;
        const int            *iptr;
        const char           *cptr;
        const unsigned char  *uptr;
        const string         *sptr;
        QColor                tempcolor;
        switch(i)
        {
          case PoincareAttributes::ID_sourceType:
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedPoint)
            {
                pointSource->setEnabled(true);
                if(pointSourceLabel)
                    pointSourceLabel->setEnabled(true);
            }
            else
            {
                pointSource->setEnabled(false);
                if(pointSourceLabel)
                    pointSourceLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedLine)
            {
                lineStart->setEnabled(true);
                if(lineStartLabel)
                    lineStartLabel->setEnabled(true);
            }
            else
            {
                lineStart->setEnabled(false);
                if(lineStartLabel)
                    lineStartLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedLine)
            {
                lineEnd->setEnabled(true);
                if(lineEndLabel)
                    lineEndLabel->setEnabled(true);
            }
            else
            {
                lineEnd->setEnabled(false);
                if(lineEndLabel)
                    lineEndLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedPlane)
            {
                planeOrigin->setEnabled(true);
                if(planeOriginLabel)
                    planeOriginLabel->setEnabled(true);
            }
            else
            {
                planeOrigin->setEnabled(false);
                if(planeOriginLabel)
                    planeOriginLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedPlane)
            {
                planeNormal->setEnabled(true);
                if(planeNormalLabel)
                    planeNormalLabel->setEnabled(true);
            }
            else
            {
                planeNormal->setEnabled(false);
                if(planeNormalLabel)
                    planeNormalLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedPlane)
            {
                planeUpAxis->setEnabled(true);
                if(planeUpAxisLabel)
                    planeUpAxisLabel->setEnabled(true);
            }
            else
            {
                planeUpAxis->setEnabled(false);
                if(planeUpAxisLabel)
                    planeUpAxisLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedLine || atts->GetSourceType() == PoincareAttributes::SpecifiedPlane)
            {
                pointDensity->setEnabled(true);
                if(pointDensityLabel)
                    pointDensityLabel->setEnabled(true);
            }
            else
            {
                pointDensity->setEnabled(false);
                if(pointDensityLabel)
                    pointDensityLabel->setEnabled(false);
            }
            if (atts->GetSourceType() == PoincareAttributes::SpecifiedPlane)
            {
                sourceRadius->setEnabled(true);
                if(sourceRadiusLabel)
                    sourceRadiusLabel->setEnabled(true);
            }
            else
            {
                sourceRadius->setEnabled(false);
                if(sourceRadiusLabel)
                    sourceRadiusLabel->setEnabled(false);
            }
            sourceType->blockSignals(true);
            sourceType->setButton(atts->GetSourceType());
            sourceType->blockSignals(false);
            break;
          case PoincareAttributes::ID_maxStepLength:
            maxStepLength->blockSignals(true);
            temp.setNum(atts->GetMaxStepLength());
            maxStepLength->setText(temp);
            maxStepLength->blockSignals(false);
            break;
          case PoincareAttributes::ID_termination:
            termination->blockSignals(true);
            temp.setNum(atts->GetTermination());
            termination->setText(temp);
            termination->blockSignals(false);
            break;
          case PoincareAttributes::ID_pointSource:
            dptr = atts->GetPointSource();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            pointSource->blockSignals(true);
            pointSource->setText(temp);
            pointSource->blockSignals(false);
            break;
          case PoincareAttributes::ID_lineStart:
            dptr = atts->GetLineStart();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            lineStart->blockSignals(true);
            lineStart->setText(temp);
            lineStart->blockSignals(false);
            break;
          case PoincareAttributes::ID_lineEnd:
            dptr = atts->GetLineEnd();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            lineEnd->blockSignals(true);
            lineEnd->setText(temp);
            lineEnd->blockSignals(false);
            break;
          case PoincareAttributes::ID_planeOrigin:
            dptr = atts->GetPlaneOrigin();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            planeOrigin->blockSignals(true);
            planeOrigin->setText(temp);
            planeOrigin->blockSignals(false);
            break;
          case PoincareAttributes::ID_planeNormal:
            dptr = atts->GetPlaneNormal();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            planeNormal->blockSignals(true);
            planeNormal->setText(temp);
            planeNormal->blockSignals(false);
            break;
          case PoincareAttributes::ID_planeUpAxis:
            dptr = atts->GetPlaneUpAxis();
            temp.sprintf("%g %g %g", dptr[0], dptr[1], dptr[2]);
            planeUpAxis->blockSignals(true);
            planeUpAxis->setText(temp);
            planeUpAxis->blockSignals(false);
            break;
          case PoincareAttributes::ID_legendFlag:
            legendFlag->blockSignals(true);
            legendFlag->setChecked(atts->GetLegendFlag());
            legendFlag->blockSignals(false);
            break;
          case PoincareAttributes::ID_lightingFlag:
            lightingFlag->blockSignals(true);
            lightingFlag->setChecked(atts->GetLightingFlag());
            lightingFlag->blockSignals(false);
            break;
          case PoincareAttributes::ID_relTol:
            relTol->blockSignals(true);
            temp.setNum(atts->GetRelTol());
            relTol->setText(temp);
            relTol->blockSignals(false);
            break;
          case PoincareAttributes::ID_absTol:
            absTol->blockSignals(true);
            temp.setNum(atts->GetAbsTol());
            absTol->setText(temp);
            absTol->blockSignals(false);
            break;
          case PoincareAttributes::ID_terminationType:
            terminationType->blockSignals(true);
            terminationType->setButton(atts->GetTerminationType());
            terminationType->blockSignals(false);
            break;
          case PoincareAttributes::ID_integrationType:
            integrationType->blockSignals(true);
            integrationType->setButton(atts->GetIntegrationType());
            integrationType->blockSignals(false);
            break;
          case PoincareAttributes::ID_showStreamlines:
            showStreamlines->blockSignals(true);
            showStreamlines->setChecked(atts->GetShowStreamlines());
            showStreamlines->blockSignals(false);
            break;
          case PoincareAttributes::ID_showPoints:
            showPoints->blockSignals(true);
            showPoints->setChecked(atts->GetShowPoints());
            showPoints->blockSignals(false);
            break;
          case PoincareAttributes::ID_pointDensity:
            pointDensity->blockSignals(true);
            temp.sprintf("%d", atts->GetPointDensity());
            pointDensity->setText(temp);
            pointDensity->blockSignals(false);
            break;
          case PoincareAttributes::ID_sourceRadius:
            sourceRadius->blockSignals(true);
            temp.setNum(atts->GetSourceRadius());
            sourceRadius->setText(temp);
            sourceRadius->blockSignals(false);
            break;
          case PoincareAttributes::ID_colorTableName:
            colorTableName->blockSignals(true);
            colorTableName->setColorTable(atts->GetColorTableName().c_str());
            colorTableName->blockSignals(false);
            break;
          case PoincareAttributes::ID_singleColor:
            tempcolor = QColor(atts->GetSingleColor().Red(),
                               atts->GetSingleColor().Green(),
                               atts->GetSingleColor().Blue());
            singleColor->blockSignals(true);
            singleColor->setButtonColor(tempcolor);
            singleColor->blockSignals(false);
            break;
          case PoincareAttributes::ID_NumberPlanes:
            NumberPlanes->blockSignals(true);
            temp.sprintf("%d", atts->GetNumberPlanes());
            NumberPlanes->setText(temp);
            NumberPlanes->blockSignals(false);
            break;
          case PoincareAttributes::ID_ColorStyle:
            ColorStyle->blockSignals(true);
            ColorStyle->setButton(atts->GetColorStyle());
            ColorStyle->blockSignals(false);
            break;
          case PoincareAttributes::ID_MaxToroidalWinding:
            MaxToroidalWinding->blockSignals(true);
            temp.sprintf("%d", atts->GetMaxToroidalWinding());
            MaxToroidalWinding->setText(temp);
            MaxToroidalWinding->blockSignals(false);
            break;
          case PoincareAttributes::ID_OverrideToroidalWinding:
            OverrideToroidalWinding->blockSignals(true);
            temp.sprintf("%d", atts->GetOverrideToroidalWinding());
            OverrideToroidalWinding->setText(temp);
            OverrideToroidalWinding->blockSignals(false);
            break;
          case PoincareAttributes::ID_HitRate:
            HitRate->blockSignals(true);
            temp.setNum(atts->GetHitRate());
            HitRate->setText(temp);
            HitRate->blockSignals(false);
            break;
          case PoincareAttributes::ID_ShowCurves:
            ShowCurves->blockSignals(true);
            ShowCurves->setButton(atts->GetShowCurves());
            ShowCurves->blockSignals(false);
            break;
          case PoincareAttributes::ID_AdjustPlane:
            AdjustPlane->blockSignals(true);
            temp.sprintf("%d", atts->GetAdjustPlane());
            AdjustPlane->setText(temp);
            AdjustPlane->blockSignals(false);
            break;
          case PoincareAttributes::ID_ShowIslands:
            ShowIslands->blockSignals(true);
            ShowIslands->setChecked(atts->GetShowIslands());
            ShowIslands->blockSignals(false);
            break;
          case PoincareAttributes::ID_Overlaps:
            Overlaps->blockSignals(true);
            Overlaps->setButton(atts->GetOverlaps());
            Overlaps->blockSignals(false);
            break;
        }
    }
}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::GetCurrentValues
//
// Purpose: 
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::GetCurrentValues(int which_widget)
{
    bool okay, doAll = (which_widget == -1);
    QString msg, temp;

    // Do maxStepLength
    if(which_widget == PoincareAttributes::ID_maxStepLength || doAll)
    {
        temp = maxStepLength->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetMaxStepLength(val);
        }

        if(!okay)
        {
            msg = tr("The value of maxStepLength was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetMaxStepLength());
            Message(msg);
            atts->SetMaxStepLength(atts->GetMaxStepLength());
        }
    }

    // Do termination
    if(which_widget == PoincareAttributes::ID_termination || doAll)
    {
        temp = termination->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetTermination(val);
        }

        if(!okay)
        {
            msg = tr("The value of termination was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetTermination());
            Message(msg);
            atts->SetTermination(atts->GetTermination());
        }
    }

    // Do pointSource
    if(which_widget == PoincareAttributes::ID_pointSource || doAll)
    {
        temp = pointSource->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetPointSource(val);
        }

        if(!okay)
        {
            const double *val = atts->GetPointSource();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of pointSource was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetPointSource(atts->GetPointSource());
        }
    }

    // Do lineStart
    if(which_widget == PoincareAttributes::ID_lineStart || doAll)
    {
        temp = lineStart->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetLineStart(val);
        }

        if(!okay)
        {
            const double *val = atts->GetLineStart();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of lineStart was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetLineStart(atts->GetLineStart());
        }
    }

    // Do lineEnd
    if(which_widget == PoincareAttributes::ID_lineEnd || doAll)
    {
        temp = lineEnd->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetLineEnd(val);
        }

        if(!okay)
        {
            const double *val = atts->GetLineEnd();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of lineEnd was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetLineEnd(atts->GetLineEnd());
        }
    }

    // Do planeOrigin
    if(which_widget == PoincareAttributes::ID_planeOrigin || doAll)
    {
        temp = planeOrigin->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetPlaneOrigin(val);
        }

        if(!okay)
        {
            const double *val = atts->GetPlaneOrigin();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of planeOrigin was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetPlaneOrigin(atts->GetPlaneOrigin());
        }
    }

    // Do planeNormal
    if(which_widget == PoincareAttributes::ID_planeNormal || doAll)
    {
        temp = planeNormal->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetPlaneNormal(val);
        }

        if(!okay)
        {
            const double *val = atts->GetPlaneNormal();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of planeNormal was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetPlaneNormal(atts->GetPlaneNormal());
        }
    }

    // Do planeUpAxis
    if(which_widget == PoincareAttributes::ID_planeUpAxis || doAll)
    {
        temp = planeUpAxis->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val[3];
            if((okay = (sscanf(temp.latin1(), "%lg %lg %lg", &val[0], &val[1], &val[2]) == 3)) == true)
                atts->SetPlaneUpAxis(val);
        }

        if(!okay)
        {
            const double *val = atts->GetPlaneUpAxis();
            QString num; num.sprintf("<%g %g %g>", 
                val[0], val[1], val[2]);
            msg = tr("The value of planeUpAxis was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(num);
            Message(msg);
            atts->SetPlaneUpAxis(atts->GetPlaneUpAxis());
        }
    }

    // Do relTol
    if(which_widget == PoincareAttributes::ID_relTol || doAll)
    {
        temp = relTol->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetRelTol(val);
        }

        if(!okay)
        {
            msg = tr("The value of relTol was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetRelTol());
            Message(msg);
            atts->SetRelTol(atts->GetRelTol());
        }
    }

    // Do absTol
    if(which_widget == PoincareAttributes::ID_absTol || doAll)
    {
        temp = absTol->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetAbsTol(val);
        }

        if(!okay)
        {
            msg = tr("The value of absTol was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetAbsTol());
            Message(msg);
            atts->SetAbsTol(atts->GetAbsTol());
        }
    }

    // Do pointDensity
    if(which_widget == PoincareAttributes::ID_pointDensity || doAll)
    {
        temp = pointDensity->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetPointDensity(val);
        }

        if(!okay)
        {
            msg = tr("The value of pointDensity was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetPointDensity());
            Message(msg);
            atts->SetPointDensity(atts->GetPointDensity());
        }
    }

    // Do sourceRadius
    if(which_widget == PoincareAttributes::ID_sourceRadius || doAll)
    {
        temp = sourceRadius->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetSourceRadius(val);
        }

        if(!okay)
        {
            msg = tr("The value of sourceRadius was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetSourceRadius());
            Message(msg);
            atts->SetSourceRadius(atts->GetSourceRadius());
        }
    }

    // Do NumberPlanes
    if(which_widget == PoincareAttributes::ID_NumberPlanes || doAll)
    {
        temp = NumberPlanes->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetNumberPlanes(val);
        }

        if(!okay)
        {
            msg = tr("The value of NumberPlanes was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetNumberPlanes());
            Message(msg);
            atts->SetNumberPlanes(atts->GetNumberPlanes());
        }
    }

    // Do MaxToroidalWinding
    if(which_widget == PoincareAttributes::ID_MaxToroidalWinding || doAll)
    {
        temp = MaxToroidalWinding->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetMaxToroidalWinding(val);
        }

        if(!okay)
        {
            msg = tr("The value of MaxToroidalWinding was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetMaxToroidalWinding());
            Message(msg);
            atts->SetMaxToroidalWinding(atts->GetMaxToroidalWinding());
        }
    }

    // Do OverrideToroidalWinding
    if(which_widget == PoincareAttributes::ID_OverrideToroidalWinding || doAll)
    {
        temp = OverrideToroidalWinding->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetOverrideToroidalWinding(val);
        }

        if(!okay)
        {
            msg = tr("The value of OverrideToroidalWinding was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetOverrideToroidalWinding());
            Message(msg);
            atts->SetOverrideToroidalWinding(atts->GetOverrideToroidalWinding());
        }
    }

    // Do HitRate
    if(which_widget == PoincareAttributes::ID_HitRate || doAll)
    {
        temp = HitRate->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            double val = temp.toDouble(&okay);
            if(okay)
                atts->SetHitRate(val);
        }

        if(!okay)
        {
            msg = tr("The value of HitRate was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetHitRate());
            Message(msg);
            atts->SetHitRate(atts->GetHitRate());
        }
    }

    // Do AdjustPlane
    if(which_widget == PoincareAttributes::ID_AdjustPlane || doAll)
    {
        temp = AdjustPlane->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetAdjustPlane(val);
        }

        if(!okay)
        {
            msg = tr("The value of AdjustPlane was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetAdjustPlane());
            Message(msg);
            atts->SetAdjustPlane(atts->GetAdjustPlane());
        }
    }

}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::Apply
//
// Purpose: 
//   Called to apply changes in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::Apply(bool ignore)
{
    if(AutoUpdate() || ignore)
    {
        GetCurrentValues(-1);
        atts->Notify();

        GetViewerMethods()->SetPlotOptions(plotType);
    }
    else
        atts->Notify();
}


//
// Qt Slot functions
//


// ****************************************************************************
// Method: QvisPoincarePlotWindow::apply
//
// Purpose: 
//   Qt slot function called when apply button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::apply()
{
    Apply(true);
}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::makeDefault
//
// Purpose: 
//   Qt slot function called when "Make default" button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::makeDefault()
{
    GetCurrentValues(-1);
    atts->Notify();
    GetViewerMethods()->SetDefaultPlotOptions(plotType);
}


// ****************************************************************************
// Method: QvisPoincarePlotWindow::reset
//
// Purpose: 
//   Qt slot function called when reset button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPoincarePlotWindow::reset()
{
    GetViewerMethods()->ResetPlotOptions(plotType);
}


void
QvisPoincarePlotWindow::sourceTypeChanged(int val)
{
    if(val != atts->GetSourceType())
    {
        atts->SetSourceType(PoincareAttributes::SourceType(val));
        Apply();
    }
}


void
QvisPoincarePlotWindow::maxStepLengthProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_maxStepLength);
    Apply();
}


void
QvisPoincarePlotWindow::terminationProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_termination);
    Apply();
}


void
QvisPoincarePlotWindow::pointSourceProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_pointSource);
    Apply();
}


void
QvisPoincarePlotWindow::lineStartProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_lineStart);
    Apply();
}


void
QvisPoincarePlotWindow::lineEndProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_lineEnd);
    Apply();
}


void
QvisPoincarePlotWindow::planeOriginProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_planeOrigin);
    Apply();
}


void
QvisPoincarePlotWindow::planeNormalProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_planeNormal);
    Apply();
}


void
QvisPoincarePlotWindow::planeUpAxisProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_planeUpAxis);
    Apply();
}


void
QvisPoincarePlotWindow::legendFlagChanged(bool val)
{
    atts->SetLegendFlag(val);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::lightingFlagChanged(bool val)
{
    atts->SetLightingFlag(val);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::relTolProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_relTol);
    Apply();
}


void
QvisPoincarePlotWindow::absTolProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_absTol);
    Apply();
}


void
QvisPoincarePlotWindow::terminationTypeChanged(int val)
{
    if(val != atts->GetTerminationType())
    {
        atts->SetTerminationType(PoincareAttributes::TerminationType(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisPoincarePlotWindow::integrationTypeChanged(int val)
{
    if(val != atts->GetIntegrationType())
    {
        atts->SetIntegrationType(PoincareAttributes::IntegrationType(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisPoincarePlotWindow::showStreamlinesChanged(bool val)
{
    atts->SetShowStreamlines(val);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::showPointsChanged(bool val)
{
    atts->SetShowPoints(val);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::pointDensityProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_pointDensity);
    Apply();
}


void
QvisPoincarePlotWindow::sourceRadiusProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_sourceRadius);
    Apply();
}


void
QvisPoincarePlotWindow::colorTableNameChanged(bool useDefault, const QString &ctName)
{
    atts->SetColorTableName(ctName.latin1());
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::singleColorChanged(const QColor &color)
{
    ColorAttribute temp(color.red(), color.green(), color.blue());
    atts->SetSingleColor(temp);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::NumberPlanesProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_NumberPlanes);
    Apply();
}


void
QvisPoincarePlotWindow::ColorStyleChanged(int val)
{
    if(val != atts->GetColorStyle())
    {
        atts->SetColorStyle(PoincareAttributes::ColorStyleType(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisPoincarePlotWindow::MaxToroidalWindingProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_MaxToroidalWinding);
    Apply();
}


void
QvisPoincarePlotWindow::OverrideToroidalWindingProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_OverrideToroidalWinding);
    Apply();
}


void
QvisPoincarePlotWindow::HitRateProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_HitRate);
    Apply();
}


void
QvisPoincarePlotWindow::ShowCurvesChanged(int val)
{
    if(val != atts->GetShowCurves())
    {
        atts->SetShowCurves(PoincareAttributes::ShowMeshType(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisPoincarePlotWindow::AdjustPlaneProcessText()
{
    GetCurrentValues(PoincareAttributes::ID_AdjustPlane);
    Apply();
}


void
QvisPoincarePlotWindow::ShowIslandsChanged(bool val)
{
    atts->SetShowIslands(val);
    SetUpdate(false);
    Apply();
}


void
QvisPoincarePlotWindow::OverlapsChanged(int val)
{
    if(val != atts->GetOverlaps())
    {
        atts->SetOverlaps(PoincareAttributes::OverlapType(val));
        SetUpdate(false);
        Apply();
    }
}


