/*****************************************************************************
*
* Copyright (c) 2000 - 2009, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400124
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include "QvisPersistentParticlesWindow.h"

#include <PersistentParticlesAttributes.h>
#include <ViewerProxy.h>

#include <qcheckbox.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <qspinbox.h>
#include <qvbox.h>
#include <qbuttongroup.h>
#include <qradiobutton.h>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineStyleWidget.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>

#include <stdio.h>
#include <string>

using std::string;

// ****************************************************************************
// Method: QvisPersistentParticlesWindow::QvisPersistentParticlesWindow
//
// Purpose: 
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPersistentParticlesWindow::QvisPersistentParticlesWindow(const int type,
                         PersistentParticlesAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisOperatorWindow(type,subj, caption, shortName, notepad)
{
    atts = subj;
}


// ****************************************************************************
// Method: QvisPersistentParticlesWindow::~QvisPersistentParticlesWindow
//
// Purpose: 
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisPersistentParticlesWindow::~QvisPersistentParticlesWindow()
{
}


// ****************************************************************************
// Method: QvisPersistentParticlesWindow::CreateWindowContents
//
// Purpose: 
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPersistentParticlesWindow::CreateWindowContents()
{
    QLabel *dummyLabel = new QLabel(tr(" "), central, "dummyLabel");

    //
    // Create the start absolute/relative path type radio buttons
    //

    QGridLayout *startLayout = new QGridLayout(topLayout, 1, 2, 10, "startLayout");

    startIndexLabel = new QLabel(tr("Index of the first time slice"), central, "startIndexLabel");
    startLayout->addWidget(startIndexLabel,0,0);
    startIndex = new QLineEdit(central, "startIndex");
    connect(startIndex, SIGNAL(returnPressed()),
            this, SLOT(startIndexProcessText()));
    startLayout->addWidget(startIndex, 0,1);


    QHBoxLayout *startPathTypeLayout = new QHBoxLayout(topLayout);
 
    // Create a group of radio buttons 
    startPathTypeButtons = new QButtonGroup( central, "startPathTypeRadioGroup" );
    startPathTypeButtons->setFrameStyle(QFrame::NoFrame);
    QLabel *startPathTypeLabel = new QLabel(startPathTypeButtons, tr("    Start Path Type"),
         central, "startPathTypeLabel");
    startPathTypeLayout->addWidget(startPathTypeLabel);
 
    QHBoxLayout *startPathTypeButtonsLayout = new QHBoxLayout(startPathTypeButtons);
    startPathTypeButtonsLayout->setSpacing(10);
    QRadioButton *rb = new QRadioButton(tr("Absolute"), startPathTypeButtons );
    rb->setChecked( TRUE );
    startPathTypeButtonsLayout->addWidget(rb);
    rb = new QRadioButton( startPathTypeButtons );
    rb->setText( tr("Relative to current time slice") );
    startPathTypeButtonsLayout->addWidget(rb);
    startPathTypeLayout->addWidget( startPathTypeButtons );
    startPathTypeLayout->addStretch(0);
    // Each time a radio button is clicked, call the startPathTypeChanged slot.
    connect(startPathTypeButtons, SIGNAL(clicked(int)),
            this, SLOT(startPathTypeChanged(int)));
 
    //
    // Create the stop absolute/relative path type radio buttons
    //

    QGridLayout *stopLayout = new QGridLayout(topLayout, 2, 2, 10, "stopLayout");

    stopLayout->addWidget(dummyLabel,0,0);

    stopIndexLabel = new QLabel(tr("Index of the last time slice"), central, "stopIndexLabel");
    stopLayout->addWidget(stopIndexLabel,1,0);
    stopIndex = new QLineEdit(central, "stopIndex");
    connect(stopIndex, SIGNAL(returnPressed()),
            this, SLOT(stopIndexProcessText()));
    stopLayout->addWidget(stopIndex, 1,1);


    QHBoxLayout *stopPathTypeLayout = new QHBoxLayout(topLayout);
 
    // Create a group of radio buttons 
    stopPathTypeButtons = new QButtonGroup( central, "stopPathTypeRadioGroup" );
    stopPathTypeButtons->setFrameStyle(QFrame::NoFrame);
    QLabel *stopPathTypeLabel = new QLabel(stopPathTypeButtons, tr("    Stop Path Type"),
         central, "stopPathTypeLabel");
    stopPathTypeLayout->addWidget(stopPathTypeLabel);
 
    QHBoxLayout *stopPathTypeButtonsLayout = new QHBoxLayout(stopPathTypeButtons);
    stopPathTypeButtonsLayout->setSpacing(10);
    rb = new QRadioButton(tr("Absolute"), stopPathTypeButtons );
    rb->setChecked( TRUE );
    stopPathTypeButtonsLayout->addWidget(rb);
    rb = new QRadioButton( stopPathTypeButtons );
    rb->setText( tr("Relative to current time slice") );
    stopPathTypeButtonsLayout->addWidget(rb);
    stopPathTypeLayout->addWidget( stopPathTypeButtons );
    stopPathTypeLayout->addStretch(0);
    // Each time a radio button is clicked, call the stopPathTypeChanged slot.
    connect(stopPathTypeButtons, SIGNAL(clicked(int)),
            this, SLOT(stopPathTypeChanged(int)));
 
    //
    // Create the stop absolute/relative path type radio buttons
    //

    QGridLayout *mainLayout = new QGridLayout(topLayout, 4, 2, 10, "mainLayout");

    mainLayout->addWidget(dummyLabel,0,0);

    strideLabel = new QLabel(tr("Skip rate between time slices"), central, "strideLabel");
    mainLayout->addWidget(strideLabel,1,0);
    stride = new QLineEdit(central, "stride");
    connect(stride, SIGNAL(returnPressed()),
            this, SLOT(strideProcessText()));
    mainLayout->addWidget(stride, 1,1);

    indexVariableLabel = new QLabel(tr("Index Variable"), central, "indexVariableLabel");
    mainLayout->addWidget(indexVariableLabel,2,0);
    int indexVariableMask = QvisVariableButton::Scalars;
    indexVariable = new QvisVariableButton(true, true, true, indexVariableMask, central, "indexVariable");
    connect(indexVariable, SIGNAL(activated(const QString&)),
            this, SLOT(indexVariableChanged(const QString&)));
    mainLayout->addWidget(indexVariable, 2,1);

    connectParticles = new QCheckBox(tr("Connect Particles"), central, "connectParticles");
    connect(connectParticles, SIGNAL(toggled(bool)),
            this, SLOT(connectParticlesChanged(bool)));
    mainLayout->addWidget(connectParticles, 3,0);
}


// ****************************************************************************
// Method: QvisPersistentParticlesWindow::UpdateWindow
//
// Purpose: 
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPersistentParticlesWindow::UpdateWindow(bool doAll)
{
    QString temp;
    double r;

    for(int i = 0; i < atts->NumAttributes(); ++i)
    {
        if(!doAll)
        {
            if(!atts->IsSelected(i))
            {
                continue;
            }
        }

        const double         *dptr;
        const float          *fptr;
        const int            *iptr;
        const char           *cptr;
        const unsigned char  *uptr;
        const string         *sptr;
        QColor                tempcolor;
        switch(i)
        {
          case PersistentParticlesAttributes::ID_startIndex:
            startIndex->blockSignals(true);
            temp.sprintf("%d", atts->GetStartIndex());
            startIndex->setText(temp);
            startIndex->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_startPathType:
            startPathTypeButtons->blockSignals(true);
            startPathTypeButtons->setButton(atts->GetStartPathType());
            startPathTypeButtons->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_stopIndex:
            stopIndex->blockSignals(true);
            temp.sprintf("%d", atts->GetStopIndex());
            stopIndex->setText(temp);
            stopIndex->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_stopPathType:
            stopPathTypeButtons->blockSignals(true);
            stopPathTypeButtons->setButton(atts->GetStopPathType());
            stopPathTypeButtons->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_stride:
            stride->blockSignals(true);
            temp.sprintf("%d", atts->GetStride());
            stride->setText(temp);
            stride->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_indexVariable:
            indexVariable->blockSignals(true);
            indexVariable->setText(atts->GetIndexVariable().c_str());
            indexVariable->blockSignals(false);
            break;
          case PersistentParticlesAttributes::ID_connectParticles:
            connectParticles->blockSignals(true);
            connectParticles->setChecked(atts->GetConnectParticles());
            connectParticles->blockSignals(false);
            break;
        }
    }
}


// ****************************************************************************
// Method: QvisPersistentParticlesWindow::GetCurrentValues
//
// Purpose: 
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisPersistentParticlesWindow::GetCurrentValues(int which_widget)
{
    bool okay, doAll = (which_widget == -1);
    QString msg, temp;

    // Do startIndex
    if(which_widget == PersistentParticlesAttributes::ID_startIndex || doAll)
    {
        temp = startIndex->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetStartIndex(val);
        }

        if(!okay)
        {
            msg = tr("The value of startIndex was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetStartIndex());
            Message(msg);
            atts->SetStartIndex(atts->GetStartIndex());
        }
    }

    // Do stopIndex
    if(which_widget == PersistentParticlesAttributes::ID_stopIndex || doAll)
    {
        temp = stopIndex->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetStopIndex(val);
        }

        if(!okay)
        {
            msg = tr("The value of stopIndex was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetStopIndex());
            Message(msg);
            atts->SetStopIndex(atts->GetStopIndex());
        }
    }

    // Do stride
    if(which_widget == PersistentParticlesAttributes::ID_stride || doAll)
    {
        temp = stride->displayText().simplifyWhiteSpace();
        okay = !temp.isEmpty();
        if(okay)
        {
            int val = temp.toInt(&okay);
            if(okay)
                atts->SetStride(val);
        }

        if(!okay)
        {
            msg = tr("The value of stride was invalid. "
                     "Resetting to the last good value of %1.").
                  arg(atts->GetStride());
            Message(msg);
            atts->SetStride(atts->GetStride());
        }
    }

}


//
// Qt Slot functions
//

void
QvisPersistentParticlesWindow::startPathTypeChanged(int button)
{
    PersistentParticlesAttributes::PathTypeEnum val =
      PersistentParticlesAttributes::PathTypeEnum(button);

    // Only do it if it changed.
    if (val != atts->GetStartPathType())
    {
        atts->SetStartPathType(val);
        Apply();
    }

    if(button == 0)
    {
        startIndexLabel->setText(tr("Index of the first time slice"));
    }
    else
    {
        startIndexLabel->setText(tr("Number of slices backwards in time"));
    }
}

void
QvisPersistentParticlesWindow::stopPathTypeChanged(int button)
{
    PersistentParticlesAttributes::PathTypeEnum val =
      PersistentParticlesAttributes::PathTypeEnum(button);

    // Only do it if it changed.
    if (val != atts->GetStopPathType())
    {
        atts->SetStopPathType(val);
        Apply();
    }

    if(button == 0)
    {
        stopIndexLabel->setText(tr("Index of the last time slice"));
    }
    else
    {
        stopIndexLabel->setText(tr("Number of slices forward in time"));
    }
}

void
QvisPersistentParticlesWindow::startIndexProcessText()
{
    GetCurrentValues(PersistentParticlesAttributes::ID_startIndex);
    Apply();
}


void
QvisPersistentParticlesWindow::stopIndexProcessText()
{
    GetCurrentValues(PersistentParticlesAttributes::ID_stopIndex);
    Apply();
}


void
QvisPersistentParticlesWindow::strideProcessText()
{
    GetCurrentValues(PersistentParticlesAttributes::ID_stride);
    Apply();
}


void
QvisPersistentParticlesWindow::indexVariableChanged(const QString &varName)
{
    atts->SetIndexVariable(varName.latin1());
    SetUpdate(false);
    Apply();
}


void
QvisPersistentParticlesWindow::connectParticlesChanged(bool val)
{
    atts->SetConnectParticles(val);
    SetUpdate(false);
    Apply();
}

